import '../models/models.dart';

final seedUserProfile = UserProfile(
  id: 'user-rammer',
  displayName: 'Rammer',
  timezone: 'Europe/Berlin',
  locale: 'de-DE',
  homeBase: 'Galvanistrasse 14, 10587 Berlin-Charlottenburg',
  workBase: 'Englische Strasse 23, 10587 Berlin-Charlottenburg',
  workStartAnchor: '08:00',
  protectedWorkWindowStart: '09:45',
  protectedWorkWindowEnd: '10:45',
  urbanSportsEnabled: true,
  defaultMovementVenue: 'House of Healing',
  createdAt: DateTime.parse('2026-04-07T08:00:00.000+02:00'),
  updatedAt: DateTime.parse('2026-04-07T08:00:00.000+02:00'),
);

final seedRays = <Ray>[
  Ray(
    id: 'ray-coding',
    slug: 'coding-apps',
    name: 'Coding / Apps',
    description: 'Technische Produktarbeit, Architektur und App-Entwicklung.',
    type: RayType.core,
    color: 'sun-amber',
    icon: 'terminal',
    sortOrder: 1,
    isActive: true,
    defaultEnergyFit: EnergyLevel.high,
    createdAt: DateTime.parse('2026-04-07T08:00:00.000+02:00'),
    updatedAt: DateTime.parse('2026-04-07T08:00:00.000+02:00'),
  ),
  Ray(
    id: 'ray-creative',
    slug: 'creative-writing',
    name: 'Kreativ / Schreiben',
    description: 'Buch, Lyrics, Szenen, Story-Fragmente und Branding-Ideen.',
    type: RayType.core,
    color: 'sun-coral',
    icon: 'pen',
    sortOrder: 2,
    isActive: true,
    defaultEnergyFit: EnergyLevel.medium,
    createdAt: DateTime.parse('2026-04-07T08:00:00.000+02:00'),
    updatedAt: DateTime.parse('2026-04-07T08:00:00.000+02:00'),
  ),
  Ray(
    id: 'ray-business',
    slug: 'business-ideas',
    name: 'Business / Produktideen',
    description: 'Monetarisierung, Plattformideen und neue Produktansaetze.',
    type: RayType.support,
    color: 'sun-gold',
    icon: 'briefcase',
    sortOrder: 3,
    isActive: true,
    defaultEnergyFit: EnergyLevel.medium,
    createdAt: DateTime.parse('2026-04-07T08:00:00.000+02:00'),
    updatedAt: DateTime.parse('2026-04-07T08:00:00.000+02:00'),
  ),
  Ray(
    id: 'ray-trading',
    slug: 'trading-finance',
    name: 'Trading / Finanzen',
    description: 'Analyse, Trading-Ideen und Bots mit klarer Begrenzung.',
    type: RayType.support,
    color: 'sun-lime',
    icon: 'chart',
    sortOrder: 4,
    isActive: true,
    defaultEnergyFit: EnergyLevel.high,
    createdAt: DateTime.parse('2026-04-07T08:00:00.000+02:00'),
    updatedAt: DateTime.parse('2026-04-07T08:00:00.000+02:00'),
  ),
  Ray(
    id: 'ray-movement',
    slug: 'movement-health',
    name: 'Bewegung / Urban Sports / Gesundheit',
    description: 'Taegliche Bewegung, Regeneration und koerperlicher Reset.',
    type: RayType.life,
    color: 'sun-teal',
    icon: 'activity',
    sortOrder: 5,
    isActive: true,
    defaultEnergyFit: EnergyLevel.medium,
    createdAt: DateTime.parse('2026-04-07T08:00:00.000+02:00'),
    updatedAt: DateTime.parse('2026-04-07T08:00:00.000+02:00'),
  ),
  Ray(
    id: 'ray-life',
    slug: 'household-cats-life',
    name: 'Haushalt / Katzen / Alltag',
    description: 'Wohnung, Katzen, Essen, kleine Orga und alltaegliche Stabilitaet.',
    type: RayType.life,
    color: 'sun-sand',
    icon: 'home',
    sortOrder: 6,
    isActive: true,
    defaultEnergyFit: EnergyLevel.low,
    createdAt: DateTime.parse('2026-04-07T08:00:00.000+02:00'),
    updatedAt: DateTime.parse('2026-04-07T08:00:00.000+02:00'),
  ),
];

final seedProjects = <Project>[
  Project(
    id: 'project-console',
    rayId: 'ray-coding',
    slug: 'console',
    name: 'Console',
    description: 'Adaptive UI System und produktiver Arbeitskern.',
    status: ProjectStatus.active,
    priority: PriorityLevel.high,
    energyFit: EnergyLevel.high,
    effortSize: 'large',
    vision: 'Ein intelligentes UI-System fuer Kontext und Fokus.',
    currentGoal: 'Adaptive UI Struktur fuer den Sonnenkompass definieren',
    monetizationPotential: MonetizationPotential.high,
    timeToFirstVersion: TimeToFirstVersion.oneWeek,
    proofOfOutput: ProofOfOutputType.prototype,
    isEvergreen: true,
    createdAt: DateTime.parse('2026-04-07T08:00:00.000+02:00'),
    updatedAt: DateTime.parse('2026-04-07T08:00:00.000+02:00'),
  ),
  Project(
    id: 'project-crazy-chess',
    rayId: 'ray-coding',
    slug: 'crazy-chess',
    name: 'Crazy Chess / RammerSchach',
    description: 'Schachsystem mit eigenen Regeln, Modi und Spielideen.',
    status: ProjectStatus.ready,
    priority: PriorityLevel.high,
    energyFit: EnergyLevel.high,
    effortSize: 'large',
    vision: 'Ein eigenstaendiges Schach- und Regelsystem mit Rammer-DNA.',
    currentGoal: 'Spielregeln und Kernmechaniken stabilisieren',
    monetizationPotential: MonetizationPotential.medium,
    timeToFirstVersion: TimeToFirstVersion.twoWeeks,
    proofOfOutput: ProofOfOutputType.prototype,
    isEvergreen: true,
    createdAt: DateTime.parse('2026-04-07T08:00:00.000+02:00'),
    updatedAt: DateTime.parse('2026-04-07T08:00:00.000+02:00'),
  ),
  Project(
    id: 'project-free-workouts',
    rayId: 'ray-business',
    slug: 'free-workouts',
    name: 'Free-Workouts',
    description: 'Kleine, sofort nutzbare Workout-Produkte fuer volle Tage.',
    status: ProjectStatus.active,
    priority: PriorityLevel.high,
    energyFit: EnergyLevel.medium,
    effortSize: 'medium',
    vision: 'Eine einfache Fitness-Erfahrung ohne App-Overkill.',
    currentGoal: 'Landingpage plus Premium-Angebot live stellen',
    monetizationPotential: MonetizationPotential.high,
    timeToFirstVersion: TimeToFirstVersion.threeDays,
    proofOfOutput: ProofOfOutputType.landingPage,
    isEvergreen: false,
    createdAt: DateTime.parse('2026-04-07T08:00:00.000+02:00'),
    updatedAt: DateTime.parse('2026-04-07T08:00:00.000+02:00'),
  ),
  Project(
    id: 'project-kunststaub',
    rayId: 'ray-creative',
    slug: 'kunststaub-fm',
    name: 'Kunststaub.fm',
    description: 'Kreative Musik- und Markenwelt mit eigener Aesthetik.',
    status: ProjectStatus.ready,
    priority: PriorityLevel.medium,
    energyFit: EnergyLevel.medium,
    effortSize: 'medium',
    vision: 'Eine eigenstaendige kreative Plattform mit klarer Identitaet.',
    currentGoal: 'Markenkern und erste visuelle Landingpage definieren',
    monetizationPotential: MonetizationPotential.medium,
    timeToFirstVersion: TimeToFirstVersion.oneWeek,
    proofOfOutput: ProofOfOutputType.prototype,
    isEvergreen: true,
    createdAt: DateTime.parse('2026-04-07T08:00:00.000+02:00'),
    updatedAt: DateTime.parse('2026-04-07T08:00:00.000+02:00'),
  ),
];

final seedIdeas = <Idea>[
  Idea(
    id: 'idea-console-context-bar',
    rayId: 'ray-coding',
    projectId: 'project-console',
    title: 'Console - Kontextleiste fuer Windows Explorer',
    summary: 'Adaptive Shortcuts auf Basis des aktiven Desktop-Kontexts.',
    description:
        'Wenn Windows Explorer aktiv ist, zeigt die Console passende Aktionen und Shortcuts auf dem Handy.',
    status: IdeaStatus.captured,
    priority: PriorityLevel.medium,
    confidence: 0.86,
    sourceType: IdeaSourceType.manualText,
    sourceText: 'Kontextleiste fuer Explorer mit adaptiven Shortcuts',
    capturedAt: DateTime.parse('2026-04-07T18:10:00.000+02:00'),
    suggestedNextStep: 'Als UI-Skizze und Flow konkretisieren.',
    activationReadiness: ActivationReadiness.candidateThisWeek,
    monetizationPotential: MonetizationPotential.medium,
    timeToFirstVersion: TimeToFirstVersion.threeDays,
    proofOfOutput: ProofOfOutputType.prototype,
    tags: ['ui', 'flutter', 'windows', 'adaptive'],
    createdByAi: false,
    aiNotes: '',
    createdAt: DateTime.parse('2026-04-07T18:10:00.000+02:00'),
    updatedAt: DateTime.parse('2026-04-07T18:10:00.000+02:00'),
  ),
  Idea(
    id: 'idea-workouts-premium-pack',
    rayId: 'ray-business',
    projectId: 'project-free-workouts',
    title: 'Premium-Paket fuer volle Tage',
    summary: 'Sieben Home-Workouts fuer Tage mit wenig Zeit oder Energie.',
    description:
        'Ein kleines verkaeufliches Paket als erster echter Zahlungs-Test fuer Free-Workouts.',
    status: IdeaStatus.candidate,
    priority: PriorityLevel.high,
    confidence: 0.92,
    sourceType: IdeaSourceType.manualText,
    sourceText: 'Premium Paket mit 7 Workouts und einfacher Landingpage',
    capturedAt: DateTime.parse('2026-04-07T19:10:00.000+02:00'),
    suggestedNextStep: 'Paketinhalt, Preis und CTA definieren.',
    activationReadiness: ActivationReadiness.candidateToday,
    monetizationPotential: MonetizationPotential.high,
    timeToFirstVersion: TimeToFirstVersion.threeDays,
    proofOfOutput: ProofOfOutputType.firstRevenue,
    tags: ['fitness', 'web', 'pricing', 'launch'],
    createdByAi: false,
    aiNotes: '',
    createdAt: DateTime.parse('2026-04-07T19:10:00.000+02:00'),
    updatedAt: DateTime.parse('2026-04-07T19:10:00.000+02:00'),
  ),
  Idea(
    id: 'idea-kunststaub-brand-page',
    rayId: 'ray-creative',
    projectId: 'project-kunststaub',
    title: 'Kunststaub visuelle Startseite',
    summary: 'Markenseite mit starkem Einstieg statt sofort voller Plattform.',
    description:
        'Erst die Atmosphaere und das Versprechen schaerfen, dann weitere Module bauen.',
    status: IdeaStatus.parked,
    priority: PriorityLevel.medium,
    confidence: 0.73,
    sourceType: IdeaSourceType.manualText,
    sourceText: 'Kunststaub braucht zuerst eine starke Brand-Seite',
    capturedAt: DateTime.parse('2026-04-07T20:00:00.000+02:00'),
    suggestedNextStep: 'Moodboard und Hero-Text ausarbeiten.',
    activationReadiness: ActivationReadiness.candidateThisWeek,
    monetizationPotential: MonetizationPotential.medium,
    timeToFirstVersion: TimeToFirstVersion.oneWeek,
    proofOfOutput: ProofOfOutputType.prototype,
    tags: ['branding', 'creative', 'landing-page'],
    createdByAi: false,
    aiNotes: '',
    createdAt: DateTime.parse('2026-04-07T20:00:00.000+02:00'),
    updatedAt: DateTime.parse('2026-04-07T20:00:00.000+02:00'),
  ),
];

final seedMovementPlan = MovementPlan(
  id: 'movement-2026-04-08',
  date: DateTime.parse('2026-04-08T00:00:00.000+02:00'),
  energyLevel: EnergyLevel.medium,
  venue: 'House of Healing',
  activityType: MovementActivityType.barre,
  plannedStart: DateTime.parse('2026-04-08T17:30:00.000+02:00'),
  plannedDurationMinutes: 60,
  status: MovementStatus.planned,
  bookingSource: 'Urban Sports Club',
  notes: 'Default Reset nach Arbeit.',
  createdAt: DateTime.parse('2026-04-08T08:00:00.000+02:00'),
  updatedAt: DateTime.parse('2026-04-08T08:00:00.000+02:00'),
);

final seedDailyRoutineBlocks = <DailyRoutineBlock>[
  const DailyRoutineBlock(
    id: 'routine-breakfast',
    userId: 'user-rammer',
    name: 'Fruehstueck',
    category: RoutineCategory.meal,
    defaultStartTime: '08:30',
    defaultDurationMinutes: 30,
    flexibility: Flexibility.semiFlexible,
    isDaily: true,
    isActive: true,
    notes: 'Erste Mahlzeit als echter Energieanker.',
  ),
  const DailyRoutineBlock(
    id: 'routine-lunch',
    userId: 'user-rammer',
    name: 'Mittagessen',
    category: RoutineCategory.meal,
    defaultStartTime: '13:00',
    defaultDurationMinutes: 45,
    flexibility: Flexibility.fixed,
    isDaily: true,
    isActive: true,
    notes: 'Mittags moeglichst ohne Tasking.',
  ),
  const DailyRoutineBlock(
    id: 'routine-dinner',
    userId: 'user-rammer',
    name: 'Abendessen',
    category: RoutineCategory.meal,
    defaultStartTime: '19:30',
    defaultDurationMinutes: 45,
    flexibility: Flexibility.semiFlexible,
    isDaily: true,
    isActive: true,
    notes: 'Dritte Mahlzeit als Runterfahranker.',
  ),
  const DailyRoutineBlock(
    id: 'routine-hygiene-morning',
    userId: 'user-rammer',
    name: 'Koerperhygiene morgens',
    category: RoutineCategory.recovery,
    defaultStartTime: '07:50',
    defaultDurationMinutes: 20,
    flexibility: Flexibility.fixed,
    isDaily: true,
    isActive: true,
    notes: 'Morgenpflege ohne Verhandlung.',
  ),
  const DailyRoutineBlock(
    id: 'routine-hygiene-evening',
    userId: 'user-rammer',
    name: 'Koerperhygiene abends',
    category: RoutineCategory.recovery,
    defaultStartTime: '22:20',
    defaultDurationMinutes: 20,
    flexibility: Flexibility.semiFlexible,
    isDaily: true,
    isActive: true,
    notes: 'Abendpflege als Schlafvorbereitung.',
  ),
  const DailyRoutineBlock(
    id: 'routine-cats',
    userId: 'user-rammer',
    name: 'Katzen fuettern und Katzenklo',
    category: RoutineCategory.cats,
    defaultStartTime: '08:05',
    defaultDurationMinutes: 15,
    flexibility: Flexibility.fixed,
    isDaily: true,
    isActive: true,
    notes: 'Morgens und abends kurz sichtbar halten.',
  ),
  const DailyRoutineBlock(
    id: 'routine-household-reset',
    userId: 'user-rammer',
    name: 'Taeglicher Haushaltsreset',
    category: RoutineCategory.household,
    defaultStartTime: '20:20',
    defaultDurationMinutes: 25,
    flexibility: Flexibility.semiFlexible,
    isDaily: true,
    isActive: true,
    notes: 'Geschirr, Boden, kleine Ordnung, keine Eskalation.',
  ),
  const DailyRoutineBlock(
    id: 'routine-water',
    userId: 'user-rammer',
    name: 'Regelmaessig trinken',
    category: RoutineCategory.recovery,
    defaultDurationMinutes: 5,
    flexibility: Flexibility.flexible,
    isDaily: true,
    isActive: true,
    notes: 'Mehrmals tagsueber sichtbar erinnern.',
  ),
];

final seedRhythmTasks = <RhythmTask>[
  const RhythmTask(
    id: 'rhythm-fitness',
    title: 'Fitness ausser Haus',
    category: 'movement',
    frequencyDays: 2,
    durationMinutes: 90,
    defaultWindow: '17:30-19:00',
    outsideHome: true,
    notes:
        'Urban Sports als Standard. Fokus auf Yoga, Massage, Pilates oder Beachvolleyball.',
  ),
  const RhythmTask(
    id: 'rhythm-laundry',
    title: 'Waesche',
    category: 'household',
    frequencyDays: 2,
    durationMinutes: 60,
    defaultWindow: '18:30-20:00',
    outsideHome: false,
    notes: 'Alle zwei Tage statt aufstauen.',
  ),
];

final seedFixedSlots = <FixedSlot>[
  const FixedSlot(
    id: 'fixed-daily-mon',
    title: 'Scrum Daily',
    dayOfWeek: DateTime.monday,
    startTime: '10:15',
    endTime: '10:30',
    category: 'meeting',
    isFixed: true,
  ),
  const FixedSlot(
    id: 'fixed-daily-tue',
    title: 'Scrum Daily',
    dayOfWeek: DateTime.tuesday,
    startTime: '10:15',
    endTime: '10:30',
    category: 'meeting',
    isFixed: true,
  ),
  const FixedSlot(
    id: 'fixed-daily-wed',
    title: 'Scrum Daily',
    dayOfWeek: DateTime.wednesday,
    startTime: '10:15',
    endTime: '10:30',
    category: 'meeting',
    isFixed: true,
  ),
  const FixedSlot(
    id: 'fixed-daily-thu',
    title: 'Scrum Daily',
    dayOfWeek: DateTime.thursday,
    startTime: '10:15',
    endTime: '10:30',
    category: 'meeting',
    isFixed: true,
  ),
  const FixedSlot(
    id: 'fixed-daily-fri',
    title: 'Scrum Daily',
    dayOfWeek: DateTime.friday,
    startTime: '10:15',
    endTime: '10:30',
    category: 'meeting',
    isFixed: true,
  ),
  const FixedSlot(
    id: 'fixed-planning-1',
    title: 'Sprint Planning Teil 1',
    dayOfWeek: DateTime.tuesday,
    startTime: '09:45',
    endTime: '10:15',
    category: 'planning',
    isFixed: true,
  ),
  const FixedSlot(
    id: 'fixed-planning-2',
    title: 'Sprint Planning Teil 2',
    dayOfWeek: DateTime.tuesday,
    startTime: '11:00',
    endTime: '12:00',
    category: 'planning',
    isFixed: true,
  ),
  const FixedSlot(
    id: 'fixed-support',
    title: 'DEV-Support / Abstimmung',
    dayOfWeek: DateTime.thursday,
    startTime: '11:00',
    endTime: '11:30',
    category: 'support',
    isFixed: true,
  ),
  const FixedSlot(
    id: 'fixed-refinement',
    title: 'Backlog Refinement',
    dayOfWeek: DateTime.thursday,
    startTime: '15:00',
    endTime: '16:00',
    category: 'planning',
    isFixed: true,
  ),
  const FixedSlot(
    id: 'fixed-review',
    title: 'Sprint Review',
    dayOfWeek: DateTime.friday,
    startTime: '10:00',
    endTime: '11:00',
    category: 'review',
    isFixed: true,
  ),
  const FixedSlot(
    id: 'fixed-retro',
    title: 'Sprint Retrospektive',
    dayOfWeek: DateTime.friday,
    startTime: '13:30',
    endTime: '15:00',
    category: 'retro',
    isFixed: true,
  ),
];

final seedOrbitItems = <OrbitItem>[
  OrbitItem(
    id: 'orbit-build-console',
    itemType: OrbitItemType.project,
    itemId: 'project-console',
    role: OrbitRole.primaryFocus,
    focusDate: DateTime.parse('2026-04-08T00:00:00.000+02:00'),
    reason: 'Build Orbit fuer den Sonnenkompass-Kern in Console.',
    activatedAt: DateTime.parse('2026-04-08T08:15:00.000+02:00'),
    createdAt: DateTime.parse('2026-04-08T08:15:00.000+02:00'),
  ),
  OrbitItem(
    id: 'orbit-money-workouts',
    itemType: OrbitItemType.project,
    itemId: 'project-free-workouts',
    role: OrbitRole.secondaryFocus,
    focusDate: DateTime.parse('2026-04-08T00:00:00.000+02:00'),
    reason: 'Monetization Orbit fuer erstes Marktfeedback und erste Einnahmen.',
    activatedAt: DateTime.parse('2026-04-08T08:16:00.000+02:00'),
    createdAt: DateTime.parse('2026-04-08T08:16:00.000+02:00'),
  ),
  OrbitItem(
    id: 'orbit-movement',
    itemType: OrbitItemType.ray,
    itemId: 'ray-movement',
    role: OrbitRole.supportFocus,
    focusDate: DateTime.parse('2026-04-08T00:00:00.000+02:00'),
    reason: 'Taeglicher koerperlicher Reset bleibt gesetzt.',
    activatedAt: DateTime.parse('2026-04-08T08:17:00.000+02:00'),
    createdAt: DateTime.parse('2026-04-08T08:17:00.000+02:00'),
  ),
];

final seedFocusDay = FocusDay(
  id: 'focusday-2026-04-08',
  date: DateTime.parse('2026-04-08T00:00:00.000+02:00'),
  workMode: WorkMode.homeOffice,
  energyLevel: EnergyLevel.medium,
  primaryOrbitItemId: 'orbit-build-console',
  secondaryOrbitItemIds: ['orbit-money-workouts', 'orbit-movement'],
  movementPlanId: 'movement-2026-04-08',
  mustDoTaskIds: const [],
  optionalTaskIds: const [],
  dailyNote:
      'Arbeit bleibt Vormittagskern. Danach Build auf Console, Vermarktungsfenster fuer Free-Workouts, Urban Sports als Reset.',
  distractionLog: null,
  dayReview: null,
  createdAt: DateTime.parse('2026-04-08T08:20:00.000+02:00'),
  updatedAt: DateTime.parse('2026-04-08T08:20:00.000+02:00'),
);
